import {faker} from 'ember-cli-mirage';

export default function(){
  return faker.random.arrayElement([
    '+99 Laps',
    'Accident',
    'Accident / fire',
    'Accident damage',
    'Airbox fire',
    'Alternator',
    'Axle',
    'Battery',
    'Black flagged',
    'Brake balance',
    'Brakes',
    'Broken Wing',
    'Chassis',
    'Chassis damage',
    'Clutch',
    'Collision',
    'Compressor',
    'Cooling',
    'Crankshaft',
    'DNF',
    'DNS',
    'Damage',
    'Did not start',
    'Differential',
    'Disqualified',
    'Distributor',
    'Drive train',
    'Drive-shaft',
    'Driver Unwell',
    'ERS',
    'Electrical',
    'Electronics',
    'Energy storage system',
    'Engine',
    'Engine electrics',
    'Engine misfire',
    'Excluded',
    'Exhaust pipe',
    'Exhaust/differential',
    'Fatal Accident',
    'Fire',
    'Fire damage',
    'Front wing',
    'Fuel Leak',
    'Fuel Pipe',
    'Fuel Pressure',
    'Fuel Pump',
    'Fuel Rig',
    'Fuel System',
    'Gear',
    'Gearbox',
    'Half Shaft',
    'Handling',
    'Heat shield fire',
    'Hydraulics',
    'Ignition',
    'Injection',
    'Injured',
    'Injury',
    'KERS',
    'Launch control',
    'Loose wheel',
    'Loss of drive',
    'Magneto',
    'Mechanical',
    'Not Classified',
    'Not Started',
    'Oil Leak',
    'Oil Pressure',
    'Oil Pump',
    'Oil fire',
    'Oil line',
    'Oil pipe',
    'Oil system',
    'Out Of Fuel',
    'Over Heating',
    'Physical',
    'Pitlane fire',
    'Pneumatics',
    'Power Unit',
    'Power box',
    'Power loss',
    'Power steering',
    'Power unit',
    'Practice accident',
    'Puncture',
    'Puncture damage',
    'Radiator',
    'Radiator damage',
    'Ran out of fuel',
    'Rear axle',
    'Rear suspension',
    'Rear wing',
    'Rear wing issue',
    'Retired',
    'Retirement',
    'Safety Concerns',
    'Safety belt',
    'Spin',
    'Spun Off',
    'Stalled on Grid',
    'Steering',
    'Steering damage',
    'Suspension',
    'Suspension damage',
    'Technical',
    'Throttle',
    'Throttle sensor',
    'Track rod',
    'Transmission',
    'Turbo',
    'Tyre',
    'Tyre deflation',
    'Tyre failure',
    'Unwell',
    'Vibration',
    'Vibrations',
    'Water Leak',
    'Water Pump',
    'Water leak',
    'Water pipe',
    'Water pressure',
    'Water pump',
    'Wheel',
    'Wheel Bearing',
    'Wheel issue',
    'Wheel nut',
    'Wheel problem',
    'Wheel rim',
    'Wiring loom',
    'Withdrawn',
    'Withdrew'
  ]);
}
